### ISSUE TITLE
[Bug] Dial timepicker when input is empty

### ISSUE THREAD

**Issue by zutitziot4324332** [dhutaryan/ngx-mat-timepicker#100]
steps to reproduce:
1. open https://dhutaryan.github.io/ngx-mat-timepicker/
2. clear input in "Dial timepicker (24h format)"
3. open dial timepicker
4. click OK without changing anything

![timepicker](https://github.com/dhutaryan/ngx-mat-timepicker/assets/145750766/4a6d214c-87e1-48e7-ac05-1141f2c776ed)

expected behaviour:
I expect the input will change to 8:41, but it is empty

![timepicker_empty](https://github.com/dhutaryan/ngx-mat-timepicker/assets/145750766/d1dc5b1b-b13b-4708-90ec-c17acc082fbe)

"Input timepicker (24h format)" works as expected

**Comment by dhutaryan** [comment]
Fixed: v16.0.1, v15.0.2
