### ISSUE TITLE
[Bug] Timepicker toggle button does not change color when opened

### ISSUE THREAD

**Issue by k45jfi534kt** [dhutaryan/ngx-mat-timepicker#109]
Angular material datepicker changes toggle button color when opened (always primary color)
![datepicker](https://github.com/dhutaryan/ngx-mat-timepicker/assets/151139329/24cd7703-9c51-462a-8fdb-7a16fdf500f8)

ngx-mat-timepicker does not change color
![timepicker](https://github.com/dhutaryan/ngx-mat-timepicker/assets/151139329/3127dd67-ef59-4872-9957-1e3feba84a53)

**Comment by dhutaryan** [comment]
Hey, nice catch, thank you. I totally forgot about it. By the way, I've changed the default color as well. It uses `icon` property in `foreground` palette (the same as angular material).

Fixed in:
- 17.0.1
- 16.0.2
- 15.0.3
