### ISSUE TITLE
M3 support?

### ISSUE THREAD

**Issue by 003marek** [dhutaryan/ngx-mat-timepicker#132]
Does it support Material V3? Or are there any plans to support it in the future?

**Comment by dhutaryan** [comment]
There is only one difference:
> Color: New color mappings and compatibility with dynamic color
Angular team will support M3 in an upcoming minor (likely 17.2). So, I'll take a look what I can do after it.

**Comment by dhutaryan** [comment]
`18.0.0` with M3 support has been released
