### ISSUE TITLE
[Bug] Attributes and controls

### ISSUE THREAD

**Issue by jfc-ddev** [dhutaryan/ngx-mat-timepicker#139]
- Currently allows letters and special characters to be entered. It should only allow numbers to be entered.

- It does not allow you to change the translations of the cancel and accept buttons. It is currently not parameterized.

**Comment by dhutaryan** [comment]
You are right about buttons. Will add the strings to `Intl` class.
About fields: are you talking about inputs for hours and minutes? You can enter letters but it will change to numbers anyway. Don't see any concerns here.

**Comment by jfc-ddev** [comment]
Yes, I am referring to the dial mode inputs. It is true that it does not accept characters, but it is confusing that a numeric input allows to show characters. This is only seen in web mode, because in mobile mode only the numeric keypad is shown.

**Comment by dhutaryan** [comment]
Fixed in:
`12.5.0`
`13.2.0`
`14.2.0`
`15.2.0`
`16.2.0`
`17.4.0`

If you have any issues/questions, feel free to create an issue.
