### ISSUE TITLE
Special characters and input controls in dial mode

### ISSUE THREAD

**Issue by jfc-ddev** [dhutaryan/ngx-mat-timepicker#144]
The following settings have been found in version 17.4.0:

- Currently allow special characters. Only numbers should be allowed. 

( ( Shift || Alt) + 'some key') 

For example =>  |@#~€¬[]!"·$%&/()= 

![image](https://github.com/dhutaryan/ngx-mat-timepicker/assets/156062845/afdd0763-835a-4462-bd8e-d035b6921646)

- Backspace does not work, and does not allow deleting entered numbers. You can only change the value with the up and down keys, but it behaves strangely.

Greetings.

**Comment by dhutaryan** [comment]
My fault. Fixed in:
`12.5.1`
`13.2.1`
`14.2.1`
`15.2.1`
`16.2.1`
`17.4.1`

Hopefully with no surprises 😄
