### ISSUE TITLE
🚨Library styles affects global styling

### ISSUE THREAD

**Issue by k3nsei** [dhutaryan/ngx-mat-timepicker#149]
When I were trying to replace `ngx-mat-timepicker` from @tonysamperi (which is very shity quality and forces to use his luxon replacement library) with `@dhutaryan/ngx-mat-timepicker`. I found that provided mixin is affecting global scope styles. Giving some gray background to inputs, but they should stay white in my project. 

![image](https://github.com/dhutaryan/ngx-mat-timepicker/assets/190422/475296d7-5a28-4e14-bd13-9461358d8303)

I found those two places where this library styles are escaping to global scope and affect project styles.

https://github.com/dhutaryan/ngx-mat-timepicker/blob/cd8cedc6bffdd2c79232fbc748f385a5e90fcb40/projects/mat-timepicker/_timepicker-theme.scss#L96

https://github.com/dhutaryan/ngx-mat-timepicker/blob/cd8cedc6bffdd2c79232fbc748f385a5e90fcb40/projects/mat-timepicker/_timepicker-theme.scss#L105

**Comment by k3nsei** [comment]
@dhutaryan btw. could you also update compatibility table in readme by reversing order to have latest version of angular on top? I think that way it would be more obvious, when I were reviewing this library if it's good enough to be used, I almost skipped it thinking it's super old and not supporting modern angular versions.

**Comment by dhutaryan** [comment]
Good point. Thank you.

**Comment by k3nsei** [comment]
@dhutaryan I'm seeing that you already deploying fix. Thanks you for quick response and for that library <3

Finally I could remove this from my project. @tonysamperi should be burning in hell for forcing his shit to be bundled with UI component.

![image](https://github.com/dhutaryan/ngx-mat-timepicker/assets/190422/1248b5a5-3927-42d1-afe1-9b6dafdd6153)

**Comment by dhutaryan** [comment]
Thank you. 

Fixed in:
`12.5.2`
`13.2.2`
`14.2.2`
`15.2.2`
`16.2.2`
`17.4.2`
