### ISSUE TITLE
Unable to change locale for time adapter

### ISSUE THREAD

**Issue by k3nsei** [dhutaryan/ngx-mat-timepicker#153]
### Problem

As this provider is using existing `LOCALE_ID` angular is ignoring value provided by me.

https://github.com/dhutaryan/ngx-mat-timepicker/blob/78c58b5c26717c23a8a2108d02ae424b04bac9a9/projects/mat-timepicker/src/lib/adapter/time-adapter.ts#L10

I've been trying like that, bo zero effect always getting `en-US` instead of `en-GB`.

![image](https://github.com/dhutaryan/ngx-mat-timepicker/assets/190422/f4b0231d-44ce-41b0-ba8c-5fdc408fc552)

To make it work I needed to do override provider for `TimeAdapter`.

![image](https://github.com/dhutaryan/ngx-mat-timepicker/assets/190422/7b945222-0631-43bd-ae04-180c2b22636e)

### Suggested solution

`NativeDateTimeAdapter` is injecting `MAT_TIME_LOCALE` as optional, so `LOCALE_ID` could be also injected as fallback.https://github.com/dhutaryan/ngx-mat-timepicker/blob/78c58b5c26717c23a8a2108d02ae424b04bac9a9/projects/mat-timepicker/src/lib/adapter/native-date-time-adapter.ts#L17

```typescript
@Injectable()
export class NativeDateTimeAdapter extends TimeAdapter<Date> {
  constructor(
    @Optional() @Inject(MAT_TIME_LOCALE) matTimeLocale: string | null,
    @Inject(LOCALE_ID) fallbackLocale: string
  ) {
    super();
    super.setLocale(matTimeLocale || fallbackLocale);
  }

 // ...
}
```

**Comment by dhutaryan** [comment]
No-no, override `LOCALE_ID`

**Comment by dhutaryan** [comment]
So, this is related to one feature that I wanted to implement. I'd like to make implementation closer to standalone components. It should help.

**Comment by dhutaryan** [comment]
So, now you can use `provideNativeDateTimeAdapter` function as provider and override `MAT_TIME_LOCALE` for each component separately. Tested it on your stackblitz. It works.

Implemented in:
`15.3.0`
`16.3.0`
`17.5.0`
