### ISSUE TITLE
Keyboard mode is unusable with keyboard

### ISSUE THREAD

**Issue by k3nsei** [dhutaryan/ngx-mat-timepicker#160]
When I open timepicker popup and switch to keyboard mode I cannot change focus using `Tab` and `Shift + Tab` after focusing hours input. Also could we have `⇅`? After `Hour` and `Minute` label to make it more clear for users to use up and down arrow key to change them?

![image](https://github.com/dhutaryan/ngx-mat-timepicker/assets/190422/01b59c7b-790d-4b18-bc4e-215ebe151106)

Btw. why in dial mode things like hours and minutes are focusable if user cannot interact with them?

![image](https://github.com/dhutaryan/ngx-mat-timepicker/assets/190422/9bc69680-7ab6-4e27-ba02-523f6c5b6d64)

**Comment by k3nsei** [comment]
I also believe `role="slider"` should be used in keyboard mode instead of text input.

![image](https://github.com/dhutaryan/ngx-mat-timepicker/assets/190422/6c09947f-6e5b-4666-960b-d6ca2b952435)


https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/slider_role

**Comment by k3nsei** [comment]
@dhutaryan here is small example how it could work https://stackblitz.com/edit/ng-slider-clock-as5izns?file=src%2Fmain.ts

**Comment by dhutaryan** [comment]
Not sure about `role="slider"`. I believe the usual input should work great. We should keep remember that we should follow material design as much as possible. 

Tab key fixed in:
`17.5.1`
`16.3.1`
`15.3.1`
`14.3.2`
`13.2.3`
`12.5.3`

**Comment by k3nsei** [comment]
@dhutaryan native `<input type="time">` have role slider.

**Comment by k3nsei** [comment]
@dhutaryan Anyway from spec of material design time picker user should be able to type there using keyboard https://m3.material.io/components/time-pickers/guidelines#14894e49-3cb0-49f0-80ad-932cdb00bb1c

**Comment by k3nsei** [comment]
@dhutaryan here are also new ideas how you can improve input behaviours https://stackblitz.com/edit/simple-timpe-picker-mz96hfs?file=src%2Ftime-picker%2Ftime-picker.component.ts
