### ISSUE TITLE
In keyboard mode can't type using numpad

### ISSUE THREAD

**Issue by k3nsei** [dhutaryan/ngx-mat-timepicker#165]
When switching to keyboard mode I'm able only to use normal numeric keys but not those from numpad.

Issue is here instead of using `Digit` keys it should be ``Array.from({ length: 10 },  (_, i) => `${i}`)``

https://github.com/dhutaryan/ngx-mat-timepicker/blob/48aec5a2348c756d1f515774665ff25ec8634d1e/projects/mat-timepicker/src/lib/time-input-base.ts#L27

And here instead of `DIGIT_KEYS.includes(event.code)` should be `DIGIT_KEYS.includes(event.key)`

https://github.com/dhutaryan/ngx-mat-timepicker/blob/48aec5a2348c756d1f515774665ff25ec8634d1e/projects/mat-timepicker/src/lib/time-input-base.ts#L63

![image](https://github.com/dhutaryan/ngx-mat-timepicker/assets/190422/0f98a368-430d-47db-9698-5fb635632f34)

**Comment by dhutaryan** [comment]
As I remember `key` is deprecated. I've checked numpad as well and it worked. Anyway, I can check it again in a week only, unfortunately.

**Comment by k3nsei** [comment]
Key is not deprecated if something was added to web it's stays forever.

**Comment by k3nsei** [comment]
@dhutaryan maybe you are using apple product and they could have different behaviour than windows or linux. But on windows it isn't working as codes for them starts with `Numpad`.

**Comment by manuelK1234** [comment]
The same for me, numpad input does not work on windows. I would appreciate if this will be fixed

**Comment by dhutaryan** [comment]
I have checked it on windows and it worked. Hm... Anyway, I will be able to check it in a few days. Please, be patient. Thank you for PR.

**Comment by k3nsei** [comment]
Really I don't know how it could work, as numpad keys are like `Numpad0`, `Numpad1` etc. From code standpoint it make no sense.

**Comment by dhutaryan** [comment]
Fixed in:
`12.5.4`
`13.2.4`
`14.2.4`
`15.4.0`
`16.4.0`
`17.6.0`
