### ISSUE TITLE
A11Y: Closing timepicker does not return focus to previously focused element

### ISSUE THREAD

**Issue by 201549BL** [dhutaryan/ngx-mat-timepicker#167]
When closing the timepicker, it does not return the focus to the previously focused elements. Instead the focus resets to the top of the document. 

We are using the timepicker within another dialog. This means that when closing the timepicker, the focus escapes the dialog which is problematic for accessibility reasons. 

https://github.com/dhutaryan/ngx-mat-timepicker/assets/70838414/bac02f64-7a06-4cf7-b79e-8b0a0edc8863

The behaviour of MatDatePicker is to return the focus to the previously focused element.

**Comment by dhutaryan** [comment]
Fixed in:
`15.4.0`
`16.4.0`
`17.6.0`
