### ISSUE TITLE
Rxjs import errors

### ISSUE THREAD

**Issue by maks-ua** [dhutaryan/ngx-mat-timepicker#178]
After installed the package and run build got some rxjs import errors. Here is one of them:

`./node_modules/@dhutaryan/ngx-mat-timepicker/fesm2022/dhutaryan-ngx-mat-timepicker.mjs:521:124-136 - Error: export 'debounceTime' (imported as 'debounceTime') was not found in 'rxjs' (possible exports: ArgumentOutOfRangeError, AsyncSubject, BehaviorSubject, ConnectableObservable, EMPTY, EmptyError, GroupedObservable, NEVER, Notification, NotificationKind, ObjectUnsubscribedError, Observable, ReplaySubject, Scheduler, Subject, Subscriber, Subscription, TimeoutError, UnsubscriptionError, VirtualAction, VirtualTimeScheduler, animationFrame, animationFrameScheduler, asap, asapScheduler, async, asyncScheduler, bindCallback, bindNodeCallback, combineLatest, concat, config, defer, empty, forkJoin, from, fromEvent, fromEventPattern, generate, identity, iif, interval, isObservable, merge, never, noop, observable, of, onErrorResumeNext, pairs, partition, pipe, queue, queueScheduler, race, range, scheduled, throwError, timer, using, zip)`

Install rxjs package didnt help.

I'm not sure if the problem is in my code. Never had that before. Could you give me some advice?

"@dhutaryan/ngx-mat-timepicker": "^17.6.0"
Angular v17
node: 20.16.0 | 18.20.4

**Comment by dhutaryan** [comment]
Hey, what version of `rxjs` do you use?

**Comment by dhutaryan** [comment]
@maks-ua how is it going? Did you fix your issue?
