### ISSUE TITLE
Incorrect `@include` statement for typography in m2 theme if typography config is not supplied

### ISSUE THREAD

**Issue by dPreininger** [dhutaryan/ngx-mat-timepicker#180]
If typography config is not specified and m2 theme is used, applying the theme fails.
This is because else branch has incorrect `@include` statement, where the mixin can't be found.

Error occurs in file projects/mat-timepicker/themes/m2/_theme.scss, line 21.

Line should be: `@include typography.m2-typography($typography);`, seems like else branch wasn't updated when m3 support was added.

I will open a PR with the fix.

**Comment by dhutaryan** [comment]
Nice catch. Thank you.

**Comment by dhutaryan** [comment]
Fixed in `18.0.2`. Thank you for the issue and PR
