### ISSUE TITLE
@dhutaryan/ngx-mat-timepicker" has an incompatible peer dependency to "@angular/material

### ISSUE THREAD

**Issue by raulidavid** [dhutaryan/ngx-mat-timepicker#187]
Using package manager: npm
Collecting installed dependencies...
Found 64 dependencies.
Fetching dependency metadata from registry...
                  Package "@dhutaryan/ngx-mat-timepicker" has an incompatible peer dependency to "@angular/material" (requires "^17.0.0", would install "18.2.5").

**Comment by dhutaryan** [comment]
Hey, what timepicker and material version do you use?

**Comment by dhutaryan** [comment]
Hope you fixed that by using a correct version. Closing this issue
