### ISSUE TITLE
[Feature] add option to change mat-time-period-item text (AM/PM)

### ISSUE THREAD

**Issue by JayAhn2** [dhutaryan/ngx-mat-timepicker#188]
As I found AM/PM text is hardcoded and doesn't have option to change it by locale. 

https://github.com/dhutaryan/ngx-mat-timepicker/blob/63306f84eafaa028c0b12d16fd174a5d5f36e502/projects/mat-timepicker/src/lib/time-period.html#L10

Would you please give us option to change the text with custom MatTimepickerIntl?

Many thanks.

**Comment by dhutaryan** [comment]
Fixed in:
`15.4.2`
`16.4.2`
`17.6.2`
`v18.0.3`
