### ISSUE TITLE
Request to switch MatTimepickerIntl properties to function/accessors

### ISSUE THREAD

**Issue by Cubelaster** [dhutaryan/ngx-mat-timepicker#189]
So I am in need of implementing various internationalizations for the component. 
We have our translations stored in txt files for various reasons, one being real time modification; but it could very well be a Db and ultimately it does not matter much I think. 

Now, I would appreciate it if MatTimepickerIntl would have a function/accessor instead of string for translations.
This is because I can change localization on the fly and while I am able to reset values for public properties on change, it would be easier to have a function that does it on the fly. 
So, instead of `inputsTitle: string;` I'd like `inputsTitle: string | () => string;`

Even better, ideally I would like to have something akin to how AgGrid does it: 
`this.getLocaleText = (params: GetLocaleTextParams): string => {
			return LocalizationService.get(`ag_grid.${params.key}`); 
		};
// LocalizationService is our custom translations provider and ag_grid is our custom token for clarity of entries`

In this way, there only exists 1 single function to read the value of a localizable string and I never have to do anything else about it.
Each params.key is property name (so for instance, 'inputsTitle') and instead of writing hardcoded values in my custom classes, I would be able to just set 1 function to read values from wherever my localization storage is (implementation for reading is what would be overridable).

Also, it's weird localization is not (initially) bound to both translations and hour format?

**Comment by dhutaryan** [comment]
I added `changes` property. So, if you have a new string and need to update it just call `intl.changes.next()`. This is the same approach as material datepicker has. You can get string from anywhere, change them and call `intl.changes.next()` then.

Fixed in:
`15.4.3`
`16.4.3`
`17.6.3`
`18.0.4`
