### ISSUE TITLE
Support of Angular v19

### ISSUE THREAD

**Issue by k3nsei** [dhutaryan/ngx-mat-timepicker#192]
Our team is planning to migrate to Angular v19 soon.
When I did some initial research after it's release.
I found out this library has potential issues.

**Comment by dhutaryan** [comment]
Which ones? Anyway, I was gonna support v19 soon

**Comment by k3nsei** [comment]
Don't remember exactly as it was few weeks ago. But seen some errors during build.

**Comment by k3nsei** [comment]
Here as an error that I got

![image](https://github.com/user-attachments/assets/c7c44ef4-2913-4a60-b5cb-6d5b84553a7a)

**Comment by dhutaryan** [comment]
yeah, I've already seen that :)

**Comment by Sagato** [comment]
Do you need any support with this? Or will you be able to ship this soon?

**Comment by dhutaryan** [comment]
`19.0.0` has been released

**Comment by k3nsei** [comment]
@dhutaryan 🍾 👏🏻
