### ISSUE TITLE
[Feature] TouchUi mode

### ISSUE THREAD

**Issue by zutitziot4324332** [dhutaryan/ngx-mat-timepicker#98]
Angular material datepicker has "**touchUi**" property (see https://material.angular.io/components/datepicker/api).
Will something similar be available here?
Currently the modal window (openAs="dialog") looks tiny compared to the size of the entire page.

![datepicker-touch](https://github.com/dhutaryan/ngx-mat-timepicker/assets/145750766/16fe1050-444c-4458-8367-8004e288276e)
![timepicker-touch](https://github.com/dhutaryan/ngx-mat-timepicker/assets/145750766/ff358a8a-0c4b-48cd-a8d4-3d56ddc6add7)

**Comment by dhutaryan** [comment]
As I understand `touchUi` is used to make calendar more convenient for user on mobile devices. I checked timepicker on mobile devices and it looks good but maybe it will look better with bigger elements. I'll have a look what I can do.

**Comment by dhutaryan** [comment]
I added `touchUi` property and  made some elements larger. Please, take a look at it in `17.2.0` version
