### ISSUE TITLE
[Idea] use in conjuction with the mat-datepicker

### ISSUE THREAD

**Issue by sp90** [dhutaryan/ngx-mat-timepicker#99]
I just found this repo [angular/components#5648](https://github.com/angular/components/issues/5648) and i see the documentation is very limited but also the examples look very nice!

I couldnt see in past issues or in examples that you have mixed it with the mat-datepicker is it possible?

On another note please create some issues of things that needs to be done, i would love to start contributing to this package its something that are really needed for the material library

**Comment by dhutaryan** [comment]
Thank you. `mat-datepicker` and `ngx-mat-timepicker` are separate components and work separately. If we have a look at https://m3.material.io/components we will see that datepicker and timepicker are not combined. I thought to combine both components but probably not now.
